---
version: "3.9"

services:

  vscode:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    user: "vscode"
    volumes:
      - ../.:/workspace:cached
      - vscode_extensions:/home/vscode/.vscode-server/extensions
      - tabnine_settings:/home/vscode/.config/TabNine
    tty: true

volumes:
  vscode_extensions:
  tabnine_settings:
